### ISSUE TITLE
Increase Readability: Make Article Width Larger; Drop ToC

### ISSUE THREAD

**Issue by zschuessler** [able-bio/suggestion-box#14]
**Describe the bug**
When I go to an article page, I get a table of contents that takes up a large portion of the article width. This hurts readability and for casual content, it's not useful.

Here's an example:
https://able.bio/DavidLandup/introduction-to-web-scraping-with-java-jsoup--641yfyl

For readability I would really prefer something like Medium, where:

1. Text content is the focus. No sidebars/distractions.
2. Larger text content width. Currently sits at 600px at desktop, but Medium's 680px feels more readable.

By the way, thanks for this project. Medium being so unreadable these days is a huge pain, and there are no alternatives. I'd be happy to port over content if this project picks up & feedback gets implemented.

**Comment by RhettTrickett** [comment]
Hey @zschuessler - thanks for mentioning this. I was actually playing with these while fine tuning but eventually left it as it was to see if there was any feedback. 

I also think the main text column is a _liiiiittle_ bit thin I'm going to take a look at some options and will bounce them off you later this week. Will also look at toning the TOC down a bit and making it optional (toggle off etc) as other devs really like having it for their articles.

Would be great to have you on board as every user who publishes helps keep motivating us to carry on!

**Comment by RhettTrickett** [comment]
Hi @zschuessler - just an update on this.

I tried out 680px width for posts but it felt a bit stretched to read lines at that width, probably because Medium's font size is 21px so they have less words on a line, while ours is 17px. So I reviewed and experimented with the column widths of various other major publishers.

- Economist: 640px
- The Guardian: 620px
- New York Times: 600px
- BBC: 600px

In the end, 620px felt the most comfortable so have updated to that to try it out. I've also reduced the size of the ToC to tone it down slightly and will be talking to @drenther about adding an option to disable it on posts if you like.

**Comment by zschuessler** [comment]
@RhettTrickett I love the approach you took to this, well done. I think you are right, making the sidebar optional will clear up the real estate there and make the 620px look good.

By the way - the sidebar is really cool. For technical content I love it.

Really excited by the project, seeing the team's dedication to stuff like this :). (Closing this but reopen if needed)
