### ISSUE TITLE
Add more tags

### ISSUE THREAD

**Issue by ZoranPandovski** [able-bio/suggestion-box#8]
The tags option per article is limited to few topics. It would be good if more options are available per article (something similar to the GitHub project topics).

**Comment by RhettTrickett** [comment]
Agreed. The ability for users to create new article tags was restricted initially to prevent these tags from becoming too messy and unstructured. These topics actually have a nested structure.

- **JavaScript** _(Language)_
-- **React** _(Library)_
-- **Vue** _(Library)_
-- **Angular** _(Library)_
- **Python** _(Language)_
-- **Django** _(Web Framework)_
- **Github** _(Service)_
- **AWS** _(Service)_

However, I've given you permission to now create new level 0 topics (e.g. JavaScript) on the fly for now, because we can trust and manage your contributions :)

We need to come up with a better strategy that allows users to create topics (something like a communal wiki approach) but there are higher priority items (like an improved article editor) that are currently being worked on. Thanks for the suggestion about looking at Github project topics, will look into that.
